spring:
  datasource:
    url: jdbc:mysql://118.24.153.209:3306/fx?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false
    username: root
    password: 123456

